"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Internal service-to-service surface (spec §15.5: "gRPC for internal service-to-service").

Unary only. Every call here backs a request/response path — the mobile action
catalogue, the tier-4 three-key gate, the triage algorithm — with no streaming
need, so no server- or client-streaming RPC is declared.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthRequest: _TypeAlias = HealthRequest  # noqa: Y015

@_typing.final
class HealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    API_VERSION_FIELD_NUMBER: _builtins.int
    TIER4_ACTIVE_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    api_version: _builtins.str
    tier4_active: _builtins.bool
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        api_version: _builtins.str = ...,
        tier4_active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_version", b"api_version", "status", b"status", "tier4_active", b"tier4_active"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthResponse: _TypeAlias = HealthResponse  # noqa: Y015

@_typing.final
class FeatureSpec(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TIER_FIELD_NUMBER: _builtins.int
    CHANNELS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    tier: _builtins.int
    @_builtins.property
    def channels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        tier: _builtins.int = ...,
        channels: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "id", b"id", "name", b"name", "tier", b"tier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FeatureSpec: _TypeAlias = FeatureSpec  # noqa: Y015

@_typing.final
class LookupFeatureRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_ID_FIELD_NUMBER: _builtins.int
    feature_id: _builtins.str
    def __init__(
        self,
        *,
        feature_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_id", b"feature_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LookupFeatureRequest: _TypeAlias = LookupFeatureRequest  # noqa: Y015

@_typing.final
class ListFeaturesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIER_FIELD_NUMBER: _builtins.int
    tier: _builtins.int
    """0 means all tiers."""
    def __init__(
        self,
        *,
        tier: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tier", b"tier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListFeaturesRequest: _TypeAlias = ListFeaturesRequest  # noqa: Y015

@_typing.final
class ListFeaturesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def features(self) -> _containers.RepeatedCompositeFieldContainer[Global___FeatureSpec]: ...
    def __init__(
        self,
        *,
        features: _abc.Iterable[Global___FeatureSpec] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["features", b"features"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListFeaturesResponse: _TypeAlias = ListFeaturesResponse  # noqa: Y015

@_typing.final
class TriageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMPTOMS_FIELD_NUMBER: _builtins.int
    AGE_YEARS_FIELD_NUMBER: _builtins.int
    PREGNANT_FIELD_NUMBER: _builtins.int
    DURATION_DAYS_FIELD_NUMBER: _builtins.int
    age_years: _builtins.int
    pregnant: _builtins.bool
    duration_days: _builtins.int
    @_builtins.property
    def symptoms(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        symptoms: _abc.Iterable[_builtins.str] | None = ...,
        age_years: _builtins.int = ...,
        pregnant: _builtins.bool = ...,
        duration_days: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["age_years", b"age_years", "duration_days", b"duration_days", "pregnant", b"pregnant", "symptoms", b"symptoms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TriageRequest: _TypeAlias = TriageRequest  # noqa: Y015

@_typing.final
class TriageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URGENCY_FIELD_NUMBER: _builtins.int
    RECOMMENDATION_FIELD_NUMBER: _builtins.int
    RED_FLAGS_FIELD_NUMBER: _builtins.int
    urgency: _builtins.str
    recommendation: _builtins.str
    @_builtins.property
    def red_flags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        urgency: _builtins.str = ...,
        recommendation: _builtins.str = ...,
        red_flags: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recommendation", b"recommendation", "red_flags", b"red_flags", "urgency", b"urgency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TriageResponse: _TypeAlias = TriageResponse  # noqa: Y015

@_typing.final
class ActivationStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivationStatusRequest: _TypeAlias = ActivationStatusRequest  # noqa: Y015

@_typing.final
class ActivationStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIER4_ACTIVE_FIELD_NUMBER: _builtins.int
    UNMET_KEYS_FIELD_NUMBER: _builtins.int
    tier4_active: _builtins.bool
    @_builtins.property
    def unmet_keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        tier4_active: _builtins.bool = ...,
        unmet_keys: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tier4_active", b"tier4_active", "unmet_keys", b"unmet_keys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivationStatusResponse: _TypeAlias = ActivationStatusResponse  # noqa: Y015
