# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: afya_internal.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'afya_internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x66ya_internal.proto\x12\x10\x61\x66ya.internal.v1\"\x0f\n\rHealthRequest\"K\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x02 \x01(\t\x12\x14\n\x0ctier4_active\x18\x03 \x01(\x08\"G\n\x0b\x46\x65\x61tureSpec\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04tier\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x03(\t\"*\n\x14LookupFeatureRequest\x12\x12\n\nfeature_id\x18\x01 \x01(\t\"#\n\x13ListFeaturesRequest\x12\x0c\n\x04tier\x18\x01 \x01(\x05\"G\n\x14ListFeaturesResponse\x12/\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x1d.afya.internal.v1.FeatureSpec\"]\n\rTriageRequest\x12\x10\n\x08symptoms\x18\x01 \x03(\t\x12\x11\n\tage_years\x18\x02 \x01(\x05\x12\x10\n\x08pregnant\x18\x03 \x01(\x08\x12\x15\n\rduration_days\x18\x04 \x01(\x05\"L\n\x0eTriageResponse\x12\x0f\n\x07urgency\x18\x01 \x01(\t\x12\x16\n\x0erecommendation\x18\x02 \x01(\t\x12\x11\n\tred_flags\x18\x03 \x03(\t\"\x19\n\x17\x41\x63tivationStatusRequest\"D\n\x18\x41\x63tivationStatusResponse\x12\x14\n\x0ctier4_active\x18\x01 \x01(\x08\x12\x12\n\nunmet_keys\x18\x02 \x03(\t2\xca\x03\n\x0c\x41\x66yaInternal\x12K\n\x06Health\x12\x1f.afya.internal.v1.HealthRequest\x1a .afya.internal.v1.HealthResponse\x12V\n\rLookupFeature\x12&.afya.internal.v1.LookupFeatureRequest\x1a\x1d.afya.internal.v1.FeatureSpec\x12]\n\x0cListFeatures\x12%.afya.internal.v1.ListFeaturesRequest\x1a&.afya.internal.v1.ListFeaturesResponse\x12K\n\x06Triage\x12\x1f.afya.internal.v1.TriageRequest\x1a .afya.internal.v1.TriageResponse\x12i\n\x10\x41\x63tivationStatus\x12).afya.internal.v1.ActivationStatusRequest\x1a*.afya.internal.v1.ActivationStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'afya_internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=56
  _globals['_HEALTHRESPONSE']._serialized_start=58
  _globals['_HEALTHRESPONSE']._serialized_end=133
  _globals['_FEATURESPEC']._serialized_start=135
  _globals['_FEATURESPEC']._serialized_end=206
  _globals['_LOOKUPFEATUREREQUEST']._serialized_start=208
  _globals['_LOOKUPFEATUREREQUEST']._serialized_end=250
  _globals['_LISTFEATURESREQUEST']._serialized_start=252
  _globals['_LISTFEATURESREQUEST']._serialized_end=287
  _globals['_LISTFEATURESRESPONSE']._serialized_start=289
  _globals['_LISTFEATURESRESPONSE']._serialized_end=360
  _globals['_TRIAGEREQUEST']._serialized_start=362
  _globals['_TRIAGEREQUEST']._serialized_end=455
  _globals['_TRIAGERESPONSE']._serialized_start=457
  _globals['_TRIAGERESPONSE']._serialized_end=533
  _globals['_ACTIVATIONSTATUSREQUEST']._serialized_start=535
  _globals['_ACTIVATIONSTATUSREQUEST']._serialized_end=560
  _globals['_ACTIVATIONSTATUSRESPONSE']._serialized_start=562
  _globals['_ACTIVATIONSTATUSRESPONSE']._serialized_end=630
  _globals['_AFYAINTERNAL']._serialized_start=633
  _globals['_AFYAINTERNAL']._serialized_end=1091
# @@protoc_insertion_point(module_scope)
