# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# PATCHED: protoc emits a top-level `import afya_internal_pb2`, which resolves only when
# the module sits on sys.path by itself. Inside the package the generated module lives at
# afya.grpc_api.afya_internal_pb2, so the import is rewritten to the package path. This is
# the only hand-edit in this generated file; re-run the protoc command after regenerating.
from afya.grpc_api import afya_internal_pb2 as afya__internal__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in afya_internal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AfyaInternalStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/afya.internal.v1.AfyaInternal/Health',
                request_serializer=afya__internal__pb2.HealthRequest.SerializeToString,
                response_deserializer=afya__internal__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.LookupFeature = channel.unary_unary(
                '/afya.internal.v1.AfyaInternal/LookupFeature',
                request_serializer=afya__internal__pb2.LookupFeatureRequest.SerializeToString,
                response_deserializer=afya__internal__pb2.FeatureSpec.FromString,
                _registered_method=True)
        self.ListFeatures = channel.unary_unary(
                '/afya.internal.v1.AfyaInternal/ListFeatures',
                request_serializer=afya__internal__pb2.ListFeaturesRequest.SerializeToString,
                response_deserializer=afya__internal__pb2.ListFeaturesResponse.FromString,
                _registered_method=True)
        self.Triage = channel.unary_unary(
                '/afya.internal.v1.AfyaInternal/Triage',
                request_serializer=afya__internal__pb2.TriageRequest.SerializeToString,
                response_deserializer=afya__internal__pb2.TriageResponse.FromString,
                _registered_method=True)
        self.ActivationStatus = channel.unary_unary(
                '/afya.internal.v1.AfyaInternal/ActivationStatus',
                request_serializer=afya__internal__pb2.ActivationStatusRequest.SerializeToString,
                response_deserializer=afya__internal__pb2.ActivationStatusResponse.FromString,
                _registered_method=True)


class AfyaInternalServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Liveness plus the served API version and the tier-4 gate state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupFeature(self, request, context):
        """One feature by id (spec ids resolve through SPEC_ID_ALIASES); NOT_FOUND if absent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFeatures(self, request, context):
        """Features of one tier, or every feature when tier is 0.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Triage(self, request, context):
        """Febrile-illness triage (§6.3 malaria trap, §8.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivationStatus(self, request, context):
        """The §11.1 three-key activation gate as data: which keys are unmet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AfyaInternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=afya__internal__pb2.HealthRequest.FromString,
                    response_serializer=afya__internal__pb2.HealthResponse.SerializeToString,
            ),
            'LookupFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupFeature,
                    request_deserializer=afya__internal__pb2.LookupFeatureRequest.FromString,
                    response_serializer=afya__internal__pb2.FeatureSpec.SerializeToString,
            ),
            'ListFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFeatures,
                    request_deserializer=afya__internal__pb2.ListFeaturesRequest.FromString,
                    response_serializer=afya__internal__pb2.ListFeaturesResponse.SerializeToString,
            ),
            'Triage': grpc.unary_unary_rpc_method_handler(
                    servicer.Triage,
                    request_deserializer=afya__internal__pb2.TriageRequest.FromString,
                    response_serializer=afya__internal__pb2.TriageResponse.SerializeToString,
            ),
            'ActivationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivationStatus,
                    request_deserializer=afya__internal__pb2.ActivationStatusRequest.FromString,
                    response_serializer=afya__internal__pb2.ActivationStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'afya.internal.v1.AfyaInternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('afya.internal.v1.AfyaInternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AfyaInternal:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afya.internal.v1.AfyaInternal/Health',
            afya__internal__pb2.HealthRequest.SerializeToString,
            afya__internal__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afya.internal.v1.AfyaInternal/LookupFeature',
            afya__internal__pb2.LookupFeatureRequest.SerializeToString,
            afya__internal__pb2.FeatureSpec.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afya.internal.v1.AfyaInternal/ListFeatures',
            afya__internal__pb2.ListFeaturesRequest.SerializeToString,
            afya__internal__pb2.ListFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Triage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afya.internal.v1.AfyaInternal/Triage',
            afya__internal__pb2.TriageRequest.SerializeToString,
            afya__internal__pb2.TriageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afya.internal.v1.AfyaInternal/ActivationStatus',
            afya__internal__pb2.ActivationStatusRequest.SerializeToString,
            afya__internal__pb2.ActivationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
